[package]
name = "pdx"
version = "0.1.0"
edition = "2021"
authors = ["kartik4091 <pithavakartik@gmail.com>"]
description = "PDF Anti-Forensics Analysis Tool"
created = "2025-06-03 19:47:23"

[dependencies]
# Core dependencies - keep minimal for fast compile
tokio = { version = "1.35", features = ["rt", "macros"] }  # Minimal tokio features
tracing = "0.1"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }