[package]
name = "pdx"
version = "0.1.0"
edition = "2021"
authors = ["kartik4091 <pithavakartik@gmail.com>"]
description = "PDF Anti-Forensics Analysis Tool"
repository = "https://github.com/kartik4091/pdx"
license = "MIT"
keywords = ["pdf", "security", "anti-forensics", "analysis"]
categories = ["command-line-utilities", "development-tools"]
created = "2025-06-03 19:38:56"

[lib]
name = "pdx"
path = "src/lib.rs"

[[bin]]
name = "pdx"
path = "src/main.rs"

[dependencies]
# Async runtime and features
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# CLI interface
clap = { version = "4.4", features = ["derive", "env"] }
dialoguer = "0.11"
indicatif = "0.17"
console = "0.15"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# PDF processing
lopdf = "0.31"
pdf = "0.8"
printpdf = "0.6"
pdf-extract = "0.7"

# Cryptography and hashing
sha2 = "0.10"
sha3 = "0.10"
blake3 = "1.5"
base64 = "0.21"
hex = "0.4"

# Date and time
chrono = { version = "0.4", features = ["serde"] }
time = "0.3"

# Filesystem and path handling
walkdir = "2.4"
glob = "0.3"
path-clean = "1.0"

# Compression
flate2 = "1.0"
zip = "0.6"

# Data structures and algorithms
rayon = "1.8"
itertools = "0.12"
petgraph = "0.6"

# Regular expressions
regex = "1.10"
fancy-regex = "0.11"

# Utilities
bytes = "1.5"
bitflags = "2.4"
uuid = { version = "1.6", features = ["v4"] }
tempfile = "3.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_assertions = "1.4"
proptest = "1.3"
quickcheck = "1.0"
tokio-test = "0.4"
fake = { version = "2.9", features = ["derive"] }
test-case = "3.3"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false
strip = true

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
