[package]
name = "pdx"
version = "0.1.0"
edition = "2021"
authors = ["kartik4091 <pithavakartik@gmail.com>"]
description = "PDF Anti-Forensics Analysis Tool"
repository = "https://github.com/kartik4091/pdx"
license = "MIT"
keywords = ["pdf", "security", "anti-forensics", "analysis"]
categories = ["command-line-utilities", "development-tools"]
created = "2025-06-03 19:33:21"

[lib]
name = "pdx"
path = "src/lib.rs"

[[bin]]
name = "pdx"
path = "src/main.rs"

[dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# CLI
clap = { version = "4.4", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# PDF processing
lopdf = "0.31"
pdf = "0.8"

# Cryptography
sha2 = "0.10"
base64 = "0.21"

# Date and time
chrono = "0.4"

# Utilities
regex = "1.10"
bytes = "1.5"
async-trait = "0.1"

[dev-dependencies]
criterion = "0.5"
tempfile = "3.8"
pretty_assertions = "1.4"
tokio-test = "0.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
